### ISSUE TITLE
Pip: No matching distribution found for google-python-cloud-debugger

### ISSUE THREAD

**Issue by ValentinCoudert** [GoogleCloudPlatform/cloud-debug-python#8]
`pip install google-python-cloud-debugger`

(I'm inside a virtualenv, for Python 2.7)

This gives me the error:
```
  Could not find a version that satisfies the requirement google-python-cloud-debugger (from versions: )
No matching distribution found for google-python-cloud-debugger
```

**Comment by ValentinCoudert** [comment]
Ok my bad, didn't pay attention I was using python3 for the virtualenv...

**Comment by youngchingjui** [comment]
I'm on Anaconda Python 3.7 virtual environment, and I am getting this same error message. However, when I switch to an Anaconda Python 3.6 environment, I have no issue. I understand on the [PYPI](https://pypi.org/project/google-python-cloud-debugger/) page, it says this only supports Python 2.7 and 3.6. However, my GAE runtime is on Python 3.7. 

Any suggestions on how to manage these different Python environments? Am I supposed to be able to download this on debugger tool on Python 3.7? Instructions on setting up this debugger for "Compute Engine" and "Local & Elsewhere" suggest that this package should be available for Python 3.7.

<img width="965" alt="screen shot 2019-02-02 at 16 11 37" src="https://user-images.githubusercontent.com/8150872/52161769-553ea780-2705-11e9-99da-dd63fcb63d83.png">

**Comment by hrasadi** [comment]
Hi,
Please note that our support for Python 3.7 is experimental. I will investigate further and come back to you soon. In the meantime, if at all possible, please try to use Python 3.6 on your setup and see of the problem persists. This will help us understand better if this is a Python 3.7 issue or a setup issue.

**Comment by youngchingjui** [comment]
Thanks @hrasadi. I switched to a Python 3.6 virtual environment and did a pip install - no issues there. For my app.yaml file, I kept my runtime to `runtime: python37`. Then I deployed on Google App Engine. This method seems to work for now.

**Comment by hrasadi** [comment]
Starting with agent version 2.10, we explicitly support Python 3.7 in our pip repository. This should address your issue.

**Comment by moguzalp** [comment]
@hrasadi  What does it mean "agent version", currently I still fail : 

`pip install google-python-cloud-debugger==2.10`

```

Could not find a version that satisfies the requirement google-python-cloud-debugger==2.10 (from versions: )
No matching distribution found for google-python-cloud-debugger==2.10
```

for python 3.7

**Comment by smacpher-myst** [comment]
Hi,

I've recently encountered this same issue while trying to run `pip install google-python-cloud-debugger` with Python 3.7.3. Is it possible that installing the debugger through PyPI isn't supported?

Here's the output I'm getting:
`
Collecting google-python-cloud-debugger
  ERROR: Could not find a version that satisfies the requirement google-python-cloud-debugger (from versions: none)
ERROR: No matching distribution found for google-python-cloud-debugger
`

Here is my python version: `Python 3.7.3` and my pip version: `pip 19.1.1`.

Also, when running a `pip search google-python-cloud-debugger`, `google-python-debugger (2.12)` comes up as the first hit:

`
google-python-cloud-debugger (2.12)             - Python Cloud Debugger
google-cloud (0.34.0)                           - API Client library for Google Cloud
google-cloud-logger (0.2.1)                     - Google Cloud Logger Formatter
google-cloud-ndb (0.0.1)                        - NDB library for Google Cloud Datastore
google-cloud-dataflow (2.5.0)                   - Google Cloud Dataflow SDK for Python, based on Apache Beam

... etc ...
`

**Comment by mctavish** [comment]
I was able to install google-python-cloud-debugger with `Python 3.7.3` and `pip 19.1.1` using `virtualenv ENV --python=python3.7` on a debian virt.

I wonder if this is an issue with your pip setup; the "from versions: none" seems strange to me.

**Comment by bool-dev** [comment]
This is an OS + Python version issue (most likely). I think the wheel/egg have not been built to support all OSes.

Doesn't work on Mac + Py3.
Works on Mac + Py2.

**Comment by smacpher-myst** [comment]
Got it – thanks for following up.

I can confirm that still doesn't work on Mac + Python 3.7, however Mac + Python 3.6 is working for me:
`
 tmp-415b6dbade7ec003 $ python --version
Python 3.6.9
 tmp-415b6dbade7ec003 $ pip freeze
cachetools==3.1.1
google-api-python-client==1.7.11
google-auth==1.6.3
google-auth-httplib2==0.0.3
google-python-cloud-debugger==2.8
httplib2==0.14.0
pyasn1==0.4.7
pyasn1-modules==0.2.7
PyYAML==5.1.2
rsa==4.0
six==1.12.0
uritemplate==3.0.0
`

**Comment by kiptoomm** [comment]
> Starting with agent version 2.10, we explicitly support Python 3.7 in our pip repository. This should address your issue.

@hrasadi this is still not working on MacOS + Python 3.7. Any update?

**Comment by wojtek-viirtue** [comment]
> > Starting with agent version 2.10, we explicitly support Python 3.7 in our pip repository. This should address your issue.
> 
> @hrasadi this is still not working on MacOS + Python 3.7. Any update?

+1 on this.  Running on a MAC 10.15.3, and Python 3.7.6

**Comment by therefromhere** [comment]
This package is only useful inside a deployed gcloud environment, so a reasonable workaround is to exclude this package from your requirements.:

```
google-python-cloud-debugger; sys_platform == 'linux'
```

Note that you should also catch the import error as per the [quickstart example](https://cloud.google.com/debugger/docs/setup/python).

**Comment by lunaryan** [comment]
Got same error when "pip3 install google-api-python-client" on Mac with Python 3.6. Changing to pip instead of pip3 works. Weird.

**Comment by mswank923** [comment]
I have my requirements exactly as above:
google-python-cloud-debugger; sys_platform == 'linux'
I have a line in my Dockerfile to pip install -r requirements.txt. The build errors out on this package still. Building using Python 3.7 & Linux CentOS7. Is this Linux distro unsupported as well? What is the issue here?

**Comment by SubtleMetaphor** [comment]
I have the same issue on Python 3.7. Following the instructions with adding those lines of code and adding "google-python-cloud-debugger" to requirements.txt will **NOT** make it possible to debug the application in GAE. It says it's unavailable for debugging. I'm guessing it has to do with the google-python-cloud-debugger package not being possible to install, apparently even for GAE.
